### ISSUE TITLE
Migration from stripe 4.0 to latest stripe 8.x

### ISSUE THREAD

**Issue by parthadrojasa** [stripe-archive/PaymentKit#98]
I have not updated stripe from a long time and i now it seems that paymentkit is integrated into stripe. So i have used multiple things from paymentkit and i am not able to find proper thing how to migrate the code. I have some queries below.
1.  I am using PTKCardNumber like
   `let cardNumber:PTKCardNumber = PTKCardNumber(string:strCardNumber)`
2.  PTKCardTypeAmex like to determine which card is it.
3.  PTKTextField for the card like
   `PTKTextField.textByRemovingUselessSpacesFromString(str as String)` 

What is used in place of above this all in new stripe?

**Comment by benzguo** [comment]
See https://github.com/stripe/stripe-ios/issues/467
